package userdashboard;
import javax.swing.JOptionPane;
import config.usersession;

/**
 *
 * @author K
 */
public class Userprof extends javax.swing.JFrame {

 
    public Userprof() {
        initComponents();
        String fullName = usersession.fullname + " " + usersession.username;
        Name.setText("Name: " + fullName);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        Userprofile1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Name = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        fullname1 = new javax.swing.JLabel();
        Username1 = new javax.swing.JLabel();
        password1 = new javax.swing.JLabel();
        phonenumber1 = new javax.swing.JLabel();
        email1 = new javax.swing.JLabel();
        home2 = new javax.swing.JButton();
        account2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(102, 51, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Userprofile1.setBackground(new java.awt.Color(102, 51, 0));
        Userprofile1.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        Userprofile1.setForeground(new java.awt.Color(255, 255, 255));
        Userprofile1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Userprofile1.setText("User Profile");
        jPanel3.add(Userprofile1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 230, 40));

        jPanel4.setBackground(new java.awt.Color(153, 102, 0));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Name.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        Name.setForeground(new java.awt.Color(255, 255, 255));
        Name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Name.setText("User Name Here");
        jPanel4.add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 250, 40));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 0, 320, 350));

        id.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        id.setForeground(new java.awt.Color(255, 255, 255));
        id.setText("ID :");
        jPanel3.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 200, 30));

        fullname1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        fullname1.setForeground(new java.awt.Color(255, 255, 255));
        fullname1.setText("Fullname :");
        jPanel3.add(fullname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 200, 30));

        Username1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        Username1.setForeground(new java.awt.Color(255, 255, 255));
        Username1.setText("Username :");
        jPanel3.add(Username1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 200, 30));

        password1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        password1.setForeground(new java.awt.Color(255, 255, 255));
        password1.setText("Password :");
        jPanel3.add(password1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 200, 30));

        phonenumber1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        phonenumber1.setForeground(new java.awt.Color(255, 255, 255));
        phonenumber1.setText("PhoneNumber :");
        jPanel3.add(phonenumber1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, 230, 30));

        email1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        email1.setForeground(new java.awt.Color(255, 255, 255));
        email1.setText("Email :");
        jPanel3.add(email1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, 230, 30));

        home2.setBackground(new java.awt.Color(102, 51, 0));
        home2.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        home2.setForeground(new java.awt.Color(255, 255, 255));
        home2.setText("BACK");
        home2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home2ActionPerformed(evt);
            }
        });
        jPanel3.add(home2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 240, 50));

        account2.setBackground(new java.awt.Color(102, 51, 0));
        account2.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        account2.setForeground(new java.awt.Color(255, 255, 255));
        account2.setText("ACCOUNT");
        account2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                account2ActionPerformed(evt);
            }
        });
        jPanel3.add(account2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 240, 50));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1200, 350));

        jPanel5.setBackground(new java.awt.Color(102, 51, 0));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 780));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 780));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1190, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void account2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_account2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_account2ActionPerformed

    private void home2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home2ActionPerformed
        Userdashboard12 ud = new Userdashboard12();
        ud.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_home2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Userprof.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Userprof.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Userprof.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Userprof.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Userprof().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Username1;
    private javax.swing.JLabel Userprofile1;
    private javax.swing.JButton account2;
    private javax.swing.JLabel email1;
    private javax.swing.JLabel fullname1;
    private javax.swing.JButton home2;
    private javax.swing.JLabel id;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel password1;
    private javax.swing.JLabel phonenumber1;
    // End of variables declaration//GEN-END:variables
}
