

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import config.config;
import java.sql.SQLException;




public class registerForm extends javax.swing.JFrame {

    
    public registerForm() {
        setLocationRelativeTo(null);
        initComponents();
       
        confirm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
     confirm.addMouseListener(new java.awt.event.MouseAdapter() {
    public void mouseClicked(java.awt.event.MouseEvent evt) {
        confirmMouseClicked(evt);
    }
});
    
    }
     private void confirmMouseClicked(java.awt.event.MouseEvent evt) {

    String fullname = r_fname1.getText().trim();
    String username = r_uname.getText().trim();
    String email = r_email.getText().trim();
    String phonenumber = r_number.getText().trim();
    String password = String.valueOf(r_pass1.getPassword()).trim();
    String role = jComboBox1.getSelectedItem().toString();

    // ✅ EMPTY FIELD VALIDATION
    if (fullname.isEmpty() || username.isEmpty() || email.isEmpty()
            || phonenumber.isEmpty() || password.isEmpty()) {

        JOptionPane.showMessageDialog(this,
                "All fields are required.",
                "Validation Error",
                JOptionPane.WARNING_MESSAGE);
        return;
    }

    try {
        Connection con = config.getConnection();

        // ✅ CHECK EXISTING EMAIL ONLY
        String checkEmail = "SELECT id FROM tbl_user WHERE email = ?";
        PreparedStatement psEmail = con.prepareStatement(checkEmail);
        psEmail.setString(1, email);
        ResultSet rsEmail = psEmail.executeQuery();

        if (rsEmail.next()) {
            JOptionPane.showMessageDialog(this,
                    "Email already exists.",
                    "Validation Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        // ✅ INSERT USER (DEFAULT STATUS = INACTIVE)
        String sql = "INSERT INTO tbl_user (fullname, username, email, phonenumber, password, role, status) "
                   + "VALUES (?, ?, ?, ?, ?, ?, ?)";

        PreparedStatement ps = con.prepareStatement(sql);
        ps.setString(1, fullname);
        ps.setString(2, username);
        ps.setString(3, email);
        ps.setString(4, phonenumber);
        ps.setString(5, password);
        ps.setString(6, role);
        ps.setString(7, "inactive"); // ✅ inactive by default

        ps.executeUpdate();

        JOptionPane.showMessageDialog(this,
                "Registration successful! Please wait for account activation.",
                "Success",
                JOptionPane.INFORMATION_MESSAGE);

        // back to login
        loginForm lf = new loginForm();
        lf.setVisible(true);
        lf.pack();
        lf.setLocationRelativeTo(null);
        this.dispose();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
                "Database error: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
    }
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        r_fname1 = new javax.swing.JTextField();
        r_uname = new javax.swing.JTextField();
        r_email = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        r_number = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cancel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        confirm = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        r_conpass = new javax.swing.JPasswordField();
        r_pass1 = new javax.swing.JPasswordField();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 51, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo2.png"))); // NOI18N
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 1, 60)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("CEMETERY");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 500, -1, -1));

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 1, 60)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("PAWS & PLOT");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 750));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 51, 0));
        jLabel1.setText("REGISTRATION FORM");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 45, -1, -1));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 51, 0));
        jLabel2.setText("Confirm Password:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 530, -1, -1));

        r_fname1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_fname1ActionPerformed(evt);
            }
        });
        jPanel3.add(r_fname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 420, 50));

        r_uname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_unameActionPerformed(evt);
            }
        });
        jPanel3.add(r_uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 420, 50));
        jPanel3.add(r_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 420, 50));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 51, 0));
        jLabel3.setText("Full Name:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 51, 0));
        jLabel4.setText("Username:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 51, 0));
        jLabel5.setText("Email:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, 20));

        r_number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_numberActionPerformed(evt);
            }
        });
        jPanel3.add(r_number, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 420, 50));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 51, 0));
        jLabel6.setText("Phone Number:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, -1, -1));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 51, 0));
        jLabel7.setText("Password:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, -1, -1));

        cancel.setBackground(new java.awt.Color(102, 51, 0));
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelMouseClicked(evt);
            }
        });
        cancel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Cancel");
        cancel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 60));

        jPanel3.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 680, 140, 60));

        confirm.setBackground(new java.awt.Color(102, 51, 0));
        confirm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Confirm");
        confirm.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 60));

        jPanel3.add(confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 680, 140, 60));

        r_conpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_conpassActionPerformed(evt);
            }
        });
        jPanel3.add(r_conpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 550, 420, 50));

        r_pass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_pass1ActionPerformed(evt);
            }
        });
        jPanel3.add(r_pass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, 420, 50));

        jComboBox1.setBackground(new java.awt.Color(102, 51, 0));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Super Admin", "Admin ", "Client" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 620, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 540, 750));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 752, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void r_unameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_unameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r_unameActionPerformed

    private void r_fname1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_fname1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r_fname1ActionPerformed

    private void r_numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_numberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r_numberActionPerformed

    private void cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseClicked
    loginForm lf = new loginForm(); // open login form
    lf.setVisible(true);
    lf.pack();
    lf.setLocationRelativeTo(null); 
    this.dispose();
    confirm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_cancelMouseClicked

    private void r_conpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_conpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r_conpassActionPerformed

    private void r_pass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_pass1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r_pass1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        String selected = jComboBox1.getSelectedItem().toString();
    System.out.println("Selected: " + selected);
    
    
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registerForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cancel;
    private javax.swing.JPanel confirm;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField r_conpass;
    private javax.swing.JTextField r_email;
    private javax.swing.JTextField r_fname1;
    private javax.swing.JTextField r_number;
    private javax.swing.JPasswordField r_pass1;
    private javax.swing.JTextField r_uname;
    // End of variables declaration//GEN-END:variables
}
